#!/bin/bash

cp ec2-user.pem ~/.ssh/identity

sudo yum -y install emacs mysql telnet wireshark tcpdump screen lynx links lsof

echo "installing pssh"
cd dev/pssh-2.3.1
sudo python ez_setup.py
sudo python setup.py install

echo "installing s3cmd"
wget 'http://sourceforge.net/projects/s3tools/files/latest/download?source=files'
tar xvfz s3cmd-1.5.0-beta1.tar.gz 
cd s3cmd-1.5.0-beta1
sudo python setup.py install

echo "don't forget to run s3cmd --configure !!!"

echo "Setting up cloudera repos"
wget http://archive.cloudera.com/cdh4/redhat/6/x86_64/cdh/cloudera-cdh4.repo  
sudo mv cloudera-cdh4.repo /etc/yum.repos.d/

wget http://archive.cloudera.com/cm4/redhat/5/x86_64/cm/cloudera-manager.repo
sudo mv cloudera-manager.repo /etc/yum.repos.d/

ls /etc/yum.repos.d/

echo "Installing cloudera manager stuff"
sudo yum -y install cloudera-manager-daemons 
sudo yum -y install cloudera-manager-server


echo "install JDK"
chmod 755  ./jdk-6u45-linux-x64-rpm.bin 
sudo ./jdk-6u45-linux-x64-rpm.bin 

echo "set up JAVA ENVS"
export JAVA_HOME=/usr/java/latest
export PATH=$JAVA_HOME/bin:$PATH

echo "export JAVA_HOME=/usr/java/latest" >> ~/.bashrc   
echo "export PATH=$JAVA_HOME/bin:$PATH" >> ~/.bashrc

echo "get sql connector"
wget "http://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.29.tar.gz"
gunzip  ./mysql-connector-java-5.1.29.tar.gz 
tar xvf  ./mysql-connector-java-5.1.29.tar  mysql-connector-java-5.1.29/mysql-connector-java-5.1.29-bin.jar

# is this path created as a logical link using alternatives?
#mkdir -p /usr/share/java/
sudo bash -c "cp /home/ec2-user/mysql-connector-java-5.1.29/mysql-connector-java-5.1.29-bin.jar /usr/share/java/mysql-connector-java.jar"

# 
# #mysql> grant all on *.* to 'temp'@'%' identified by 'temp' with grant option;
# 
# # the doc didn't work on RDS. I had to use:
# 
# GRANT ALL PRIVILEGES ON `%`.* TO temp@'%' IDENTIFIED BY 'temp' WITH GRANT OPTION;
# 
# #this is a workaround if using rds as the store
# GRANT ALL PRIVILEGES ON `%`.* TO scm@'%' IDENTIFIED BY 'scm' WITH GRANT OPTION;
# 
# #  On the Cloudera Manager Server host (myhost2), run the script:
# 
# /usr/share/cmf/schema/scm_prepare_database.sh mysql -h cloudera.cfuzrvhqdmqv.us-west-2.rds.amazonaws.com -u temp -ptemp --scm-host ip-10-227-56-46.us-west-2.compute.internal  scm scm scm
# 
# mysql> drop user 'temp'@'%';
# 
# mv /etc/cloudera-scm-server/db.mgmt.properties /tmp/
